name: wam
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pyyaml
  - pytest
  - matplotlib
  - pillow
  - pytorch
  - pytorch-cuda=12.1
  - pip:
      - timm
      - huggingface_hub
      - pyarrow
      - opencv-python-headless
      - h5py
      - transformers
      - sentencepiece
      - protobuf
